"""add phase3 adaptive learning and remediation models

Revision ID: 19f6e9f8e394
Revises: 9b34cd567efa
Create Date: 2026-09-05 11:19:04.820896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f6e9f8e394'
down_revision: Union[str, None] = '9b34cd567efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_difficulty'), 'learning_resources', ['difficulty'], unique=False)
    op.create_index(op.f('ix_learning_resources_id'), 'learning_resources', ['id'], unique=False)
    op.create_index(op.f('ix_learning_resources_is_active'), 'learning_resources', ['is_active'], unique=False)
    op.create_index(op.f('ix_learning_resources_resource_type'), 'learning_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_learning_resources_title'), 'learning_resources', ['title'], unique=False)
    op.create_table('competency_prerequisites',
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_competency_id', sa.UUID(), nullable=False),
    sa.Column('minimum_mastery', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competency_id', 'prerequisite_competency_id', name='uq_competency_prerequisite')
    )
    op.create_index(op.f('ix_competency_prerequisites_competency_id'), 'competency_prerequisites', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_prerequisites_id'), 'competency_prerequisites', ['id'], unique=False)
    op.create_index(op.f('ix_competency_prerequisites_prerequisite_competency_id'), 'competency_prerequisites', ['prerequisite_competency_id'], unique=False)
    op.create_table('resource_skills',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'competency_id', name='uq_resource_competency')
    )
    op.create_index(op.f('ix_resource_skills_competency_id'), 'resource_skills', ['competency_id'], unique=False)
    op.create_index(op.f('ix_resource_skills_id'), 'resource_skills', ['id'], unique=False)
    op.create_index(op.f('ix_resource_skills_resource_id'), 'resource_skills', ['resource_id'], unique=False)
    op.create_table('learning_plans',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_plans_id'), 'learning_plans', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plans_learner_id'), 'learning_plans', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learning_plans_role_id'), 'learning_plans', ['role_id'], unique=False)
    op.create_index(op.f('ix_learning_plans_status'), 'learning_plans', ['status'], unique=False)
    op.create_table('learning_plan_modules',
    sa.Column('learning_plan_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('prior_mastery', sa.Float(), nullable=False),
    sa.Column('current_mastery', sa.Float(), nullable=False),
    sa.Column('target_mastery', sa.Float(), nullable=False),
    sa.Column('gap', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('role_weight', sa.Float(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('adaptation_count', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('next_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_plan_id'], ['learning_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_plan_modules_competency_id'), 'learning_plan_modules', ['competency_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_modules_difficulty_level'), 'learning_plan_modules', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_learning_plan_modules_id'), 'learning_plan_modules', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plan_modules_learning_plan_id'), 'learning_plan_modules', ['learning_plan_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_modules_status'), 'learning_plan_modules', ['status'], unique=False)
    op.create_table('learning_activities',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=40), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['learning_plan_modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_activities_activity_type'), 'learning_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_learning_activities_created_at'), 'learning_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_activities_id'), 'learning_activities', ['id'], unique=False)
    op.create_index(op.f('ix_learning_activities_learner_id'), 'learning_activities', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learning_activities_module_id'), 'learning_activities', ['module_id'], unique=False)
    op.create_index(op.f('ix_learning_activities_resource_id'), 'learning_activities', ['resource_id'], unique=False)
    op.create_table('reassessment_attempts',
    sa.Column('learning_plan_module_id', sa.UUID(), nullable=False),
    sa.Column('assessment_submission_id', sa.UUID(), nullable=True),
    sa.Column('prior_mastery', sa.Float(), nullable=False),
    sa.Column('posterior_mastery', sa.Float(), nullable=False),
    sa.Column('prior_gap', sa.Float(), nullable=False),
    sa.Column('posterior_gap', sa.Float(), nullable=False),
    sa.Column('gap_delta', sa.Float(), nullable=False),
    sa.Column('target_mastery', sa.Float(), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('adaptation_action', sa.String(length=40), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_submission_id'], ['assessment_submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learning_plan_module_id'], ['learning_plan_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reassessment_attempts_adaptation_action'), 'reassessment_attempts', ['adaptation_action'], unique=False)
    op.create_index(op.f('ix_reassessment_attempts_assessment_submission_id'), 'reassessment_attempts', ['assessment_submission_id'], unique=False)
    op.create_index(op.f('ix_reassessment_attempts_attempted_at'), 'reassessment_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_reassessment_attempts_id'), 'reassessment_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_reassessment_attempts_learning_plan_module_id'), 'reassessment_attempts', ['learning_plan_module_id'], unique=False)
    op.create_index(op.f('ix_reassessment_attempts_result'), 'reassessment_attempts', ['result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reassessment_attempts_result'), table_name='reassessment_attempts')
    op.drop_index(op.f('ix_reassessment_attempts_learning_plan_module_id'), table_name='reassessment_attempts')
    op.drop_index(op.f('ix_reassessment_attempts_id'), table_name='reassessment_attempts')
    op.drop_index(op.f('ix_reassessment_attempts_attempted_at'), table_name='reassessment_attempts')
    op.drop_index(op.f('ix_reassessment_attempts_assessment_submission_id'), table_name='reassessment_attempts')
    op.drop_index(op.f('ix_reassessment_attempts_adaptation_action'), table_name='reassessment_attempts')
    op.drop_table('reassessment_attempts')
    op.drop_index(op.f('ix_learning_activities_resource_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_module_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_learner_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_created_at'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_activity_type'), table_name='learning_activities')
    op.drop_table('learning_activities')
    op.drop_index(op.f('ix_learning_plan_modules_status'), table_name='learning_plan_modules')
    op.drop_index(op.f('ix_learning_plan_modules_learning_plan_id'), table_name='learning_plan_modules')
    op.drop_index(op.f('ix_learning_plan_modules_id'), table_name='learning_plan_modules')
    op.drop_index(op.f('ix_learning_plan_modules_difficulty_level'), table_name='learning_plan_modules')
    op.drop_index(op.f('ix_learning_plan_modules_competency_id'), table_name='learning_plan_modules')
    op.drop_table('learning_plan_modules')
    op.drop_index(op.f('ix_learning_plans_status'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_role_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_learner_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_id'), table_name='learning_plans')
    op.drop_table('learning_plans')
    op.drop_index(op.f('ix_resource_skills_resource_id'), table_name='resource_skills')
    op.drop_index(op.f('ix_resource_skills_id'), table_name='resource_skills')
    op.drop_index(op.f('ix_resource_skills_competency_id'), table_name='resource_skills')
    op.drop_table('resource_skills')
    op.drop_index(op.f('ix_competency_prerequisites_prerequisite_competency_id'), table_name='competency_prerequisites')
    op.drop_index(op.f('ix_competency_prerequisites_id'), table_name='competency_prerequisites')
    op.drop_index(op.f('ix_competency_prerequisites_competency_id'), table_name='competency_prerequisites')
    op.drop_table('competency_prerequisites')
    op.drop_index(op.f('ix_learning_resources_title'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_resource_type'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_is_active'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_id'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_difficulty'), table_name='learning_resources')
    op.drop_table('learning_resources')
    # ### end Alembic commands ###
