"""create_employer_and_mandate_tables

Revision ID: 1e6f999c5454
Revises: 2864a42370ff
Create Date: 2026-08-29 13:23:34.411377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6f999c5454'
down_revision: Union[str, None] = '2864a42370ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('industry_sector', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_company_name'), 'employers', ['company_name'], unique=False)
    op.create_index(op.f('ix_employers_contact_email'), 'employers', ['contact_email'], unique=False)
    op.create_index(op.f('ix_employers_id'), 'employers', ['id'], unique=False)
    op.create_index(op.f('ix_employers_industry_sector'), 'employers', ['industry_sector'], unique=False)
    op.create_index(op.f('ix_employers_tier'), 'employers', ['tier'], unique=False)
    op.create_table('hiring_mandates',
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('openings_count', sa.Integer(), nullable=False),
    sa.Column('min_nsqf_level', sa.String(length=30), nullable=True),
    sa.Column('required_competencies_json', sa.Text(), nullable=True),
    sa.Column('salary_min_lpa', sa.Float(), nullable=False),
    sa.Column('salary_max_lpa', sa.Float(), nullable=False),
    sa.Column('retention_benchmark_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hiring_mandates_active_sector', 'hiring_mandates', ['is_active', 'sector'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_district_id'), 'hiring_mandates', ['district_id'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_employer_id'), 'hiring_mandates', ['employer_id'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_id'), 'hiring_mandates', ['id'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_is_active'), 'hiring_mandates', ['is_active'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_job_title'), 'hiring_mandates', ['job_title'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_sector'), 'hiring_mandates', ['sector'], unique=False)
    op.create_index('ix_hiring_mandates_sector_state', 'hiring_mandates', ['sector', 'state'], unique=False)
    op.create_index(op.f('ix_hiring_mandates_state'), 'hiring_mandates', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hiring_mandates_state'), table_name='hiring_mandates')
    op.drop_index('ix_hiring_mandates_sector_state', table_name='hiring_mandates')
    op.drop_index(op.f('ix_hiring_mandates_sector'), table_name='hiring_mandates')
    op.drop_index(op.f('ix_hiring_mandates_job_title'), table_name='hiring_mandates')
    op.drop_index(op.f('ix_hiring_mandates_is_active'), table_name='hiring_mandates')
    op.drop_index(op.f('ix_hiring_mandates_id'), table_name='hiring_mandates')
    op.drop_index(op.f('ix_hiring_mandates_employer_id'), table_name='hiring_mandates')
    op.drop_index(op.f('ix_hiring_mandates_district_id'), table_name='hiring_mandates')
    op.drop_index('ix_hiring_mandates_active_sector', table_name='hiring_mandates')
    op.drop_table('hiring_mandates')
    op.drop_index(op.f('ix_employers_tier'), table_name='employers')
    op.drop_index(op.f('ix_employers_industry_sector'), table_name='employers')
    op.drop_index(op.f('ix_employers_id'), table_name='employers')
    op.drop_index(op.f('ix_employers_contact_email'), table_name='employers')
    op.drop_index(op.f('ix_employers_company_name'), table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###
