"""create_foundational_models

Revision ID: 5755df1c13eb
Revises: 
Create Date: 2026-08-29 01:29:08.339977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5755df1c13eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('nqr_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_code'), 'competencies', ['code'], unique=True)
    op.create_index(op.f('ix_competencies_id'), 'competencies', ['id'], unique=False)
    op.create_index(op.f('ix_competencies_name'), 'competencies', ['name'], unique=False)
    op.create_index(op.f('ix_competencies_nqr_code'), 'competencies', ['nqr_code'], unique=False)
    op.create_index(op.f('ix_competencies_sector'), 'competencies', ['sector'], unique=False)
    op.create_index('ix_competencies_sector_code', 'competencies', ['sector', 'code'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_districts_region'), 'districts', ['region'], unique=False)
    op.create_index(op.f('ix_districts_state'), 'districts', ['state'], unique=False)
    op.create_index('ix_districts_state_region', 'districts', ['state', 'region'], unique=False)
    op.create_index(op.f('ix_districts_tier'), 'districts', ['tier'], unique=False)
    op.create_index('ix_districts_tier_region', 'districts', ['tier', 'region'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('training_centers',
    sa.Column('center_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_centers_center_code'), 'training_centers', ['center_code'], unique=True)
    op.create_index('ix_training_centers_district_active', 'training_centers', ['district_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_training_centers_district_id'), 'training_centers', ['district_id'], unique=False)
    op.create_index(op.f('ix_training_centers_id'), 'training_centers', ['id'], unique=False)
    op.create_index(op.f('ix_training_centers_name'), 'training_centers', ['name'], unique=False)
    op.create_table('learners',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('training_center_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('nsqf_level', sa.String(length=30), nullable=True),
    sa.Column('employment_readiness_score', sa.Integer(), nullable=False),
    sa.Column('overall_progress', sa.Integer(), nullable=False),
    sa.Column('ncvet_credential_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_center_id'], ['training_centers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_district_id'), 'learners', ['district_id'], unique=False)
    op.create_index('ix_learners_district_status', 'learners', ['district_id', 'status'], unique=False)
    op.create_index(op.f('ix_learners_email'), 'learners', ['email'], unique=True)
    op.create_index(op.f('ix_learners_full_name'), 'learners', ['full_name'], unique=False)
    op.create_index(op.f('ix_learners_id'), 'learners', ['id'], unique=False)
    op.create_index(op.f('ix_learners_ncvet_credential_id'), 'learners', ['ncvet_credential_id'], unique=False)
    op.create_index(op.f('ix_learners_status'), 'learners', ['status'], unique=False)
    op.create_index('ix_learners_status_readiness', 'learners', ['status', 'employment_readiness_score'], unique=False)
    op.create_index(op.f('ix_learners_training_center_id'), 'learners', ['training_center_id'], unique=False)
    op.create_table('learner_skills',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('score_percentage', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.String(length=150), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'competency_id', name='uq_learner_competency')
    )
    op.create_index(op.f('ix_learner_skills_competency_id'), 'learner_skills', ['competency_id'], unique=False)
    op.create_index(op.f('ix_learner_skills_id'), 'learner_skills', ['id'], unique=False)
    op.create_index(op.f('ix_learner_skills_learner_id'), 'learner_skills', ['learner_id'], unique=False)
    op.create_index('ix_learner_skills_score', 'learner_skills', ['score_percentage'], unique=False)
    op.create_index('ix_learner_skills_verified', 'learner_skills', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learner_skills_verified', table_name='learner_skills')
    op.drop_index('ix_learner_skills_score', table_name='learner_skills')
    op.drop_index(op.f('ix_learner_skills_learner_id'), table_name='learner_skills')
    op.drop_index(op.f('ix_learner_skills_id'), table_name='learner_skills')
    op.drop_index(op.f('ix_learner_skills_competency_id'), table_name='learner_skills')
    op.drop_table('learner_skills')
    op.drop_index(op.f('ix_learners_training_center_id'), table_name='learners')
    op.drop_index('ix_learners_status_readiness', table_name='learners')
    op.drop_index(op.f('ix_learners_status'), table_name='learners')
    op.drop_index(op.f('ix_learners_ncvet_credential_id'), table_name='learners')
    op.drop_index(op.f('ix_learners_id'), table_name='learners')
    op.drop_index(op.f('ix_learners_full_name'), table_name='learners')
    op.drop_index(op.f('ix_learners_email'), table_name='learners')
    op.drop_index('ix_learners_district_status', table_name='learners')
    op.drop_index(op.f('ix_learners_district_id'), table_name='learners')
    op.drop_table('learners')
    op.drop_index(op.f('ix_training_centers_name'), table_name='training_centers')
    op.drop_index(op.f('ix_training_centers_id'), table_name='training_centers')
    op.drop_index(op.f('ix_training_centers_district_id'), table_name='training_centers')
    op.drop_index('ix_training_centers_district_active', table_name='training_centers')
    op.drop_index(op.f('ix_training_centers_center_code'), table_name='training_centers')
    op.drop_table('training_centers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_districts_tier_region', table_name='districts')
    op.drop_index(op.f('ix_districts_tier'), table_name='districts')
    op.drop_index('ix_districts_state_region', table_name='districts')
    op.drop_index(op.f('ix_districts_state'), table_name='districts')
    op.drop_index(op.f('ix_districts_region'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index('ix_competencies_sector_code', table_name='competencies')
    op.drop_index(op.f('ix_competencies_sector'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_nqr_code'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_name'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_code'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
