"""add_audit_log_indexes

Revision ID: 64477fc484ef
Revises: 7a8e9f1234bc
Create Date: 2026-08-29 14:13:42.681294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64477fc484ef'
down_revision: Union[str, None] = '7a8e9f1234bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_created_at_desc', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_desc', table_name='audit_logs')
    # ### end Alembic commands ###
