"""add_phase7_learning_interventions

Revision ID: 66127262ef91
Revises: a2fc2c14c425
Create Date: 2026-09-05 12:25:26.758534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66127262ef91'
down_revision: Union[str, None] = 'a2fc2c14c425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_interventions',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('actual_hours', sa.Float(), nullable=False),
    sa.Column('baseline_mastery', sa.Float(), nullable=True),
    sa.Column('final_mastery', sa.Float(), nullable=True),
    sa.Column('baseline_gap', sa.Float(), nullable=True),
    sa.Column('final_gap', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interventions_learner_status', 'learning_interventions', ['learner_id', 'status'], unique=False)
    op.create_index('ix_interventions_type_status', 'learning_interventions', ['intervention_type', 'status'], unique=False)
    op.create_index(op.f('ix_learning_interventions_competency_id'), 'learning_interventions', ['competency_id'], unique=False)
    op.create_index(op.f('ix_learning_interventions_id'), 'learning_interventions', ['id'], unique=False)
    op.create_index(op.f('ix_learning_interventions_intervention_type'), 'learning_interventions', ['intervention_type'], unique=False)
    op.create_index(op.f('ix_learning_interventions_learner_id'), 'learning_interventions', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learning_interventions_recommended_at'), 'learning_interventions', ['recommended_at'], unique=False)
    op.create_index(op.f('ix_learning_interventions_role_id'), 'learning_interventions', ['role_id'], unique=False)
    op.create_index(op.f('ix_learning_interventions_source'), 'learning_interventions', ['source'], unique=False)
    op.create_index(op.f('ix_learning_interventions_status'), 'learning_interventions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_interventions_status'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_source'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_role_id'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_recommended_at'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_learner_id'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_intervention_type'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_id'), table_name='learning_interventions')
    op.drop_index(op.f('ix_learning_interventions_competency_id'), table_name='learning_interventions')
    op.drop_index('ix_interventions_type_status', table_name='learning_interventions')
    op.drop_index('ix_interventions_learner_status', table_name='learning_interventions')
    op.drop_table('learning_interventions')
    # ### end Alembic commands ###
