"""add_consent_followup_outcomes_tables

Revision ID: 7360af0541ec
Revises: 64477fc484ef
Create Date: 2026-09-02 23:31:41.643098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7360af0541ec'
down_revision: Union[str, None] = '64477fc484ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_consent_type'), 'consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consents_id'), 'consents', ['id'], unique=False)
    op.create_index('ix_consents_learner_granted', 'consents', ['learner_id', 'granted'], unique=False)
    op.create_index(op.f('ix_consents_learner_id'), 'consents', ['learner_id'], unique=False)
    op.create_index('ix_consents_learner_type', 'consents', ['learner_id', 'consent_type'], unique=False)
    op.create_table('non_placement_reasons',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('associated_skill_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_non_placement_learner_reason', 'non_placement_reasons', ['learner_id', 'reason'], unique=False)
    op.create_index(op.f('ix_non_placement_reasons_associated_skill_code'), 'non_placement_reasons', ['associated_skill_code'], unique=False)
    op.create_index(op.f('ix_non_placement_reasons_id'), 'non_placement_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_non_placement_reasons_learner_id'), 'non_placement_reasons', ['learner_id'], unique=False)
    op.create_index(op.f('ix_non_placement_reasons_reason'), 'non_placement_reasons', ['reason'], unique=False)
    op.create_table('outcome_follow_ups',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('follow_up_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('response_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_follow_ups_learner_status', 'outcome_follow_ups', ['learner_id', 'status'], unique=False)
    op.create_index('ix_follow_ups_scheduled_status', 'outcome_follow_ups', ['scheduled_at', 'status'], unique=False)
    op.create_index(op.f('ix_outcome_follow_ups_follow_up_type'), 'outcome_follow_ups', ['follow_up_type'], unique=False)
    op.create_index(op.f('ix_outcome_follow_ups_id'), 'outcome_follow_ups', ['id'], unique=False)
    op.create_index(op.f('ix_outcome_follow_ups_learner_id'), 'outcome_follow_ups', ['learner_id'], unique=False)
    op.create_index(op.f('ix_outcome_follow_ups_response_status'), 'outcome_follow_ups', ['response_status'], unique=False)
    op.create_index(op.f('ix_outcome_follow_ups_scheduled_at'), 'outcome_follow_ups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_outcome_follow_ups_status'), 'outcome_follow_ups', ['status'], unique=False)
    op.create_table('self_employment_outcomes',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('enterprise_name', sa.String(length=150), nullable=False),
    sa.Column('business_activity', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('monthly_income_range', sa.String(length=50), nullable=False),
    sa.Column('business_status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_self_emp_learner_status', 'self_employment_outcomes', ['learner_id', 'verification_status'], unique=False)
    op.create_index('ix_self_emp_sector_district', 'self_employment_outcomes', ['sector', 'district_id'], unique=False)
    op.create_index(op.f('ix_self_employment_outcomes_district_id'), 'self_employment_outcomes', ['district_id'], unique=False)
    op.create_index(op.f('ix_self_employment_outcomes_id'), 'self_employment_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_self_employment_outcomes_learner_id'), 'self_employment_outcomes', ['learner_id'], unique=False)
    op.create_index(op.f('ix_self_employment_outcomes_sector'), 'self_employment_outcomes', ['sector'], unique=False)
    op.create_index(op.f('ix_self_employment_outcomes_start_date'), 'self_employment_outcomes', ['start_date'], unique=False)
    op.create_index(op.f('ix_self_employment_outcomes_verification_status'), 'self_employment_outcomes', ['verification_status'], unique=False)
    op.create_table('placement_separations',
    sa.Column('placement_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('separation_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('associated_skill_gap', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['retention_checkpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_separations_checkpoint_id'), 'placement_separations', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_placement_separations_id'), 'placement_separations', ['id'], unique=False)
    op.create_index('ix_placement_separations_placement_date', 'placement_separations', ['placement_id', 'separation_date'], unique=False)
    op.create_index(op.f('ix_placement_separations_placement_id'), 'placement_separations', ['placement_id'], unique=False)
    op.create_index('ix_placement_separations_reason', 'placement_separations', ['reason'], unique=False)
    op.create_index(op.f('ix_placement_separations_separation_date'), 'placement_separations', ['separation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_separations_separation_date'), table_name='placement_separations')
    op.drop_index('ix_placement_separations_reason', table_name='placement_separations')
    op.drop_index(op.f('ix_placement_separations_placement_id'), table_name='placement_separations')
    op.drop_index('ix_placement_separations_placement_date', table_name='placement_separations')
    op.drop_index(op.f('ix_placement_separations_id'), table_name='placement_separations')
    op.drop_index(op.f('ix_placement_separations_checkpoint_id'), table_name='placement_separations')
    op.drop_table('placement_separations')
    op.drop_index(op.f('ix_self_employment_outcomes_verification_status'), table_name='self_employment_outcomes')
    op.drop_index(op.f('ix_self_employment_outcomes_start_date'), table_name='self_employment_outcomes')
    op.drop_index(op.f('ix_self_employment_outcomes_sector'), table_name='self_employment_outcomes')
    op.drop_index(op.f('ix_self_employment_outcomes_learner_id'), table_name='self_employment_outcomes')
    op.drop_index(op.f('ix_self_employment_outcomes_id'), table_name='self_employment_outcomes')
    op.drop_index(op.f('ix_self_employment_outcomes_district_id'), table_name='self_employment_outcomes')
    op.drop_index('ix_self_emp_sector_district', table_name='self_employment_outcomes')
    op.drop_index('ix_self_emp_learner_status', table_name='self_employment_outcomes')
    op.drop_table('self_employment_outcomes')
    op.drop_index(op.f('ix_outcome_follow_ups_status'), table_name='outcome_follow_ups')
    op.drop_index(op.f('ix_outcome_follow_ups_scheduled_at'), table_name='outcome_follow_ups')
    op.drop_index(op.f('ix_outcome_follow_ups_response_status'), table_name='outcome_follow_ups')
    op.drop_index(op.f('ix_outcome_follow_ups_learner_id'), table_name='outcome_follow_ups')
    op.drop_index(op.f('ix_outcome_follow_ups_id'), table_name='outcome_follow_ups')
    op.drop_index(op.f('ix_outcome_follow_ups_follow_up_type'), table_name='outcome_follow_ups')
    op.drop_index('ix_follow_ups_scheduled_status', table_name='outcome_follow_ups')
    op.drop_index('ix_follow_ups_learner_status', table_name='outcome_follow_ups')
    op.drop_table('outcome_follow_ups')
    op.drop_index(op.f('ix_non_placement_reasons_reason'), table_name='non_placement_reasons')
    op.drop_index(op.f('ix_non_placement_reasons_learner_id'), table_name='non_placement_reasons')
    op.drop_index(op.f('ix_non_placement_reasons_id'), table_name='non_placement_reasons')
    op.drop_index(op.f('ix_non_placement_reasons_associated_skill_code'), table_name='non_placement_reasons')
    op.drop_index('ix_non_placement_learner_reason', table_name='non_placement_reasons')
    op.drop_table('non_placement_reasons')
    op.drop_index('ix_consents_learner_type', table_name='consents')
    op.drop_index(op.f('ix_consents_learner_id'), table_name='consents')
    op.drop_index('ix_consents_learner_granted', table_name='consents')
    op.drop_index(op.f('ix_consents_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_consent_type'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
