"""add_phase4_career_outcomes_and_ml_snapshots

Revision ID: d0613e3b24e7
Revises: 19f6e9f8e394
Create Date: 2026-09-05 11:36:48.412553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0613e3b24e7'
down_revision: Union[str, None] = '19f6e9f8e394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_applications',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('salary_offered', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_applications_applied_at'), 'career_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_career_applications_id'), 'career_applications', ['id'], unique=False)
    op.create_index(op.f('ix_career_applications_learner_id'), 'career_applications', ['learner_id'], unique=False)
    op.create_index(op.f('ix_career_applications_role_id'), 'career_applications', ['role_id'], unique=False)
    op.create_index(op.f('ix_career_applications_status'), 'career_applications', ['status'], unique=False)
    op.create_index('ix_career_apps_learner_applied', 'career_applications', ['learner_id', 'applied_at'], unique=False)
    op.create_index('ix_career_apps_status', 'career_applications', ['status'], unique=False)
    op.create_table('career_events',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_events_event_date'), 'career_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_career_events_event_type'), 'career_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_career_events_id'), 'career_events', ['id'], unique=False)
    op.create_index('ix_career_events_learner_date', 'career_events', ['learner_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_career_events_learner_id'), 'career_events', ['learner_id'], unique=False)
    op.create_index(op.f('ix_career_events_role_id'), 'career_events', ['role_id'], unique=False)
    op.create_index('ix_career_events_type_date', 'career_events', ['event_type', 'event_date'], unique=False)
    op.create_table('learner_projects',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_projects_completed_at'), 'learner_projects', ['completed_at'], unique=False)
    op.create_index(op.f('ix_learner_projects_id'), 'learner_projects', ['id'], unique=False)
    op.create_index('ix_learner_projects_learner_date', 'learner_projects', ['learner_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_learner_projects_learner_id'), 'learner_projects', ['learner_id'], unique=False)
    op.create_table('ml_feature_snapshots',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_feature_snapshots_feature_version'), 'ml_feature_snapshots', ['feature_version'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_id'), 'ml_feature_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_learner_id'), 'ml_feature_snapshots', ['learner_id'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_prediction_cutoff'), 'ml_feature_snapshots', ['prediction_cutoff'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_role_id'), 'ml_feature_snapshots', ['role_id'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_snapshot_date'), 'ml_feature_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_ml_snapshots_learner_cutoff', 'ml_feature_snapshots', ['learner_id', 'prediction_cutoff'], unique=False)
    op.create_index('ix_ml_snapshots_version_cutoff', 'ml_feature_snapshots', ['feature_version', 'prediction_cutoff'], unique=False)
    op.add_column('learner_outcomes', sa.Column('status', sa.String(length=50), server_default='VERIFIED', nullable=False))
    op.add_column('learner_outcomes', sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_outcomes', 'confidence')
    op.drop_column('learner_outcomes', 'status')
    op.drop_index('ix_ml_snapshots_version_cutoff', table_name='ml_feature_snapshots')
    op.drop_index('ix_ml_snapshots_learner_cutoff', table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_snapshot_date'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_role_id'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_prediction_cutoff'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_learner_id'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_id'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_feature_version'), table_name='ml_feature_snapshots')
    op.drop_table('ml_feature_snapshots')
    op.drop_index(op.f('ix_learner_projects_learner_id'), table_name='learner_projects')
    op.drop_index('ix_learner_projects_learner_date', table_name='learner_projects')
    op.drop_index(op.f('ix_learner_projects_id'), table_name='learner_projects')
    op.drop_index(op.f('ix_learner_projects_completed_at'), table_name='learner_projects')
    op.drop_table('learner_projects')
    op.drop_index('ix_career_events_type_date', table_name='career_events')
    op.drop_index(op.f('ix_career_events_role_id'), table_name='career_events')
    op.drop_index(op.f('ix_career_events_learner_id'), table_name='career_events')
    op.drop_index('ix_career_events_learner_date', table_name='career_events')
    op.drop_index(op.f('ix_career_events_id'), table_name='career_events')
    op.drop_index(op.f('ix_career_events_event_type'), table_name='career_events')
    op.drop_index(op.f('ix_career_events_event_date'), table_name='career_events')
    op.drop_table('career_events')
    op.drop_index('ix_career_apps_status', table_name='career_applications')
    op.drop_index('ix_career_apps_learner_applied', table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_status'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_role_id'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_learner_id'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_id'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_applied_at'), table_name='career_applications')
    op.drop_table('career_applications')
    # ### end Alembic commands ###
