"""create_skill_gap_tables

Revision ID: 2864a42370ff
Revises: 5755df1c13eb
Create Date: 2026-08-29 13:20:14.563286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2864a42370ff'
down_revision: Union[str, None] = '5755df1c13eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gap_analytics',
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('employer_demand_pct', sa.Float(), nullable=False),
    sa.Column('workforce_supply_pct', sa.Float(), nullable=False),
    sa.Column('deficit_pct', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('learners_affected', sa.Integer(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_analytics_competency_id'), 'skill_gap_analytics', ['competency_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analytics_deficit_pct'), 'skill_gap_analytics', ['deficit_pct'], unique=False)
    op.create_index(op.f('ix_skill_gap_analytics_district_id'), 'skill_gap_analytics', ['district_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analytics_id'), 'skill_gap_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analytics_priority_rank'), 'skill_gap_analytics', ['priority_rank'], unique=False)
    op.create_index(op.f('ix_skill_gap_analytics_severity'), 'skill_gap_analytics', ['severity'], unique=False)
    op.create_index('ix_skill_gap_deficit_severity', 'skill_gap_analytics', ['deficit_pct', 'severity'], unique=False)
    op.create_index('ix_skill_gap_district_severity', 'skill_gap_analytics', ['district_id', 'severity'], unique=False)
    op.create_table('skill_gap_interventions',
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('intervention_type', sa.String(length=60), nullable=False),
    sa.Column('target_capacity', sa.Integer(), nullable=False),
    sa.Column('budget_allocated_inr', sa.Float(), nullable=False),
    sa.Column('target_completion_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deployed_by', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_interventions_competency_id'), 'skill_gap_interventions', ['competency_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_interventions_district_id'), 'skill_gap_interventions', ['district_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_interventions_id'), 'skill_gap_interventions', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gap_interventions_intervention_type'), 'skill_gap_interventions', ['intervention_type'], unique=False)
    op.create_index(op.f('ix_skill_gap_interventions_status'), 'skill_gap_interventions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gap_interventions_status'), table_name='skill_gap_interventions')
    op.drop_index(op.f('ix_skill_gap_interventions_intervention_type'), table_name='skill_gap_interventions')
    op.drop_index(op.f('ix_skill_gap_interventions_id'), table_name='skill_gap_interventions')
    op.drop_index(op.f('ix_skill_gap_interventions_district_id'), table_name='skill_gap_interventions')
    op.drop_index(op.f('ix_skill_gap_interventions_competency_id'), table_name='skill_gap_interventions')
    op.drop_table('skill_gap_interventions')
    op.drop_index('ix_skill_gap_district_severity', table_name='skill_gap_analytics')
    op.drop_index('ix_skill_gap_deficit_severity', table_name='skill_gap_analytics')
    op.drop_index(op.f('ix_skill_gap_analytics_severity'), table_name='skill_gap_analytics')
    op.drop_index(op.f('ix_skill_gap_analytics_priority_rank'), table_name='skill_gap_analytics')
    op.drop_index(op.f('ix_skill_gap_analytics_id'), table_name='skill_gap_analytics')
    op.drop_index(op.f('ix_skill_gap_analytics_district_id'), table_name='skill_gap_analytics')
    op.drop_index(op.f('ix_skill_gap_analytics_deficit_pct'), table_name='skill_gap_analytics')
    op.drop_index(op.f('ix_skill_gap_analytics_competency_id'), table_name='skill_gap_analytics')
    op.drop_table('skill_gap_analytics')
    # ### end Alembic commands ###
