"""create_placement_and_retention_tables

Revision ID: f17d85cc0aab
Revises: 1e6f999c5454
Create Date: 2026-08-29 13:30:35.071417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17d85cc0aab'
down_revision: Union[str, None] = '1e6f999c5454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('learner_id', sa.String(length=50), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('hiring_mandate_id', sa.UUID(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('starting_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('current_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uan', sa.String(length=30), nullable=True),
    sa.Column('epfo_verification_status', sa.String(length=30), nullable=False),
    sa.Column('epfo_last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('epfo_transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hiring_mandate_id'], ['hiring_mandates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_employer_id'), 'placements', ['employer_id'], unique=False)
    op.create_index('ix_placements_employer_joined', 'placements', ['employer_id', 'joined_date'], unique=False)
    op.create_index(op.f('ix_placements_epfo_verification_status'), 'placements', ['epfo_verification_status'], unique=False)
    op.create_index(op.f('ix_placements_hiring_mandate_id'), 'placements', ['hiring_mandate_id'], unique=False)
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    op.create_index(op.f('ix_placements_job_title'), 'placements', ['job_title'], unique=False)
    op.create_index(op.f('ix_placements_joined_date'), 'placements', ['joined_date'], unique=False)
    op.create_index(op.f('ix_placements_learner_id'), 'placements', ['learner_id'], unique=False)
    op.create_index('ix_placements_learner_status', 'placements', ['learner_id', 'status'], unique=False)
    op.create_index(op.f('ix_placements_status'), 'placements', ['status'], unique=False)
    op.create_index(op.f('ix_placements_uan'), 'placements', ['uan'], unique=False)
    op.create_table('retention_checkpoints',
    sa.Column('placement_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=20), nullable=False),
    sa.Column('milestone_months', sa.Integer(), nullable=False),
    sa.Column('checkpoint_date', sa.Date(), nullable=False),
    sa.Column('is_active_at_checkpoint', sa.Boolean(), nullable=False),
    sa.Column('epfo_verified', sa.Boolean(), nullable=False),
    sa.Column('current_ctc_lpa', sa.Float(), nullable=False),
    sa.Column('wage_increment_percentage', sa.Float(), nullable=False),
    sa.Column('epfo_contribution_months', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_checkpoints_checkpoint_date'), 'retention_checkpoints', ['checkpoint_date'], unique=False)
    op.create_index(op.f('ix_retention_checkpoints_checkpoint_type'), 'retention_checkpoints', ['checkpoint_type'], unique=False)
    op.create_index(op.f('ix_retention_checkpoints_id'), 'retention_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_retention_checkpoints_placement_id'), 'retention_checkpoints', ['placement_id'], unique=False)
    op.create_index('ix_retention_checkpoints_placement_type', 'retention_checkpoints', ['placement_id', 'checkpoint_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retention_checkpoints_placement_type', table_name='retention_checkpoints')
    op.drop_index(op.f('ix_retention_checkpoints_placement_id'), table_name='retention_checkpoints')
    op.drop_index(op.f('ix_retention_checkpoints_id'), table_name='retention_checkpoints')
    op.drop_index(op.f('ix_retention_checkpoints_checkpoint_type'), table_name='retention_checkpoints')
    op.drop_index(op.f('ix_retention_checkpoints_checkpoint_date'), table_name='retention_checkpoints')
    op.drop_table('retention_checkpoints')
    op.drop_index(op.f('ix_placements_uan'), table_name='placements')
    op.drop_index(op.f('ix_placements_status'), table_name='placements')
    op.drop_index('ix_placements_learner_status', table_name='placements')
    op.drop_index(op.f('ix_placements_learner_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_joined_date'), table_name='placements')
    op.drop_index(op.f('ix_placements_job_title'), table_name='placements')
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_hiring_mandate_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_epfo_verification_status'), table_name='placements')
    op.drop_index('ix_placements_employer_joined', table_name='placements')
    op.drop_index(op.f('ix_placements_employer_id'), table_name='placements')
    op.drop_table('placements')
    # ### end Alembic commands ###
