from datetime import timedelta
import pytest
from httpx import AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.config import settings
from src.core.logging import SensitiveDataFilter, get_correlation_id, set_correlation_id
from src.core.security import (
    create_access_token,
    create_refresh_token,
    decode_access_token,
    mask_aadhaar,
    mask_email,
    mask_phone,
    redact_sensitive_payload,
)
from src.models.audit_log import AuditLog
from src.services.audit_service import audit_service


# ==============================================================================
# Sensitive Data Masking & Redaction Unit Tests
# ==============================================================================

def test_sensitive_data_masking():
    """Verify masking of emails, phone numbers, and Aadhaar numbers."""
    assert mask_email("rajesh.kumar@example.com") == "ra***@example.com"
    assert mask_email("a@b.com") == "a***@b.com"
    assert mask_phone("+919876543210") == "+91-XXXXX-XX210"
    assert mask_aadhaar("123456789012") == "XXXX-XXXX-9012"


def test_deep_payload_redaction():
    """Verify recursive redaction strips passwords, tokens, and secret keys."""
    raw_payload = {
        "user": {
            "email": "priya.sharma@domain.in",
            "password": "SuperSecretPassword123!",
            "hashed_password": "$2b$12$e0NZhX4s...hash",
            "api_key": "sk_live_9988112233",
            "access_token": "eyJhbGciOi...",
            "aadhaar_number": "999988887777",
        },
        "action": "BENEFICIARY_REGISTER",
        "metadata": {"nested_secret": "my_secret_token"},
    }

    redacted = redact_sensitive_payload(raw_payload)
    assert redacted["user"]["password"] == "[REDACTED]"
    assert redacted["user"]["hashed_password"] == "[REDACTED]"
    assert redacted["user"]["api_key"] == "[REDACTED]"
    assert redacted["user"]["access_token"] == "[REDACTED]"
    assert redacted["user"]["aadhaar_number"] == "XXXX-XXXX-7777"
    assert redacted["user"]["email"] == "pr***@domain.in"
    assert redacted["metadata"]["nested_secret"] == "[REDACTED]"


# ==============================================================================
# Security Headers & Correlation ID Middleware Tests
# ==============================================================================

@pytest.mark.asyncio
async def test_security_headers_and_correlation_id_propagation(client: AsyncClient):
    """Verify security headers and correlation ID in HTTP responses."""
    custom_corr_id = "TEST-CORR-UUID-9911"
    resp = await client.get("/health", headers={"X-Correlation-ID": custom_corr_id})

    assert resp.status_code == 200

    # 1. Verify Correlation ID Header
    assert resp.headers.get("X-Correlation-ID") == custom_corr_id

    # 2. Verify Security Headers
    assert resp.headers.get("X-Content-Type-Options") == "nosniff"
    assert resp.headers.get("X-Frame-Options") == "DENY"
    assert resp.headers.get("X-XSS-Protection") == "1; mode=block"
    assert "Strict-Transport-Security" in resp.headers
    assert "Content-Security-Policy" in resp.headers
    assert resp.headers.get("Referrer-Policy") == "strict-origin-when-cross-origin"


@pytest.mark.asyncio
async def test_automatic_correlation_id_generation(client: AsyncClient):
    """Verify requests without correlation ID receive an autogenerated KN-* header."""
    resp = await client.get("/health")
    assert resp.status_code == 200
    corr_id = resp.headers.get("X-Correlation-ID")
    assert corr_id is not None
    assert corr_id.startswith("KN-")


# ==============================================================================
# JWT Expiration & Refresh Token Strategy Tests
# ==============================================================================

def test_jwt_access_and_refresh_token_lifecycle():
    """Verify access and refresh tokens enforce distinct token type claims."""
    # 1. Access Token
    access_token = create_access_token(
        subject="user-123",
        role="MSDE_OFFICER",
        expires_delta=timedelta(minutes=30),
    )
    access_payload = decode_access_token(access_token, expected_type="access")
    assert access_payload["sub"] == "user-123"
    assert access_payload["role"] == "MSDE_OFFICER"
    assert access_payload["type"] == "access"

    # 2. Refresh Token
    refresh_token = create_refresh_token(
        subject="user-123",
        role="MSDE_OFFICER",
        expires_delta=timedelta(days=7),
    )
    refresh_payload = decode_access_token(refresh_token, expected_type="refresh")
    assert refresh_payload["sub"] == "user-123"
    assert refresh_payload["type"] == "refresh"

    # 3. Cross-type rejection
    with pytest.raises(Exception):
        # Attempting to use access token as refresh token must fail
        decode_access_token(access_token, expected_type="refresh")


import uuid
from src.core.database import AsyncSessionLocal


@pytest.mark.asyncio
async def test_auth_refresh_token_endpoint(client: AsyncClient):
    """Test POST /api/v1/auth/refresh rotates tokens successfully."""
    unique_email = f"refreshtest.{uuid.uuid4().hex[:6]}@kaushalnexus.gov.in"
    # Register a user
    reg_resp = await client.post(
        "/api/v1/auth/register",
        json={
            "email": unique_email,
            "password": "Password12345!",
            "full_name": "Token Refresh User",
            "role": "MSDE_OFFICER",
        },
    )
    assert reg_resp.status_code == 201

    # Login to get initial refresh token
    login_resp = await client.post(
        "/api/v1/auth/login",
        json={
            "email": unique_email,
            "password": "Password12345!",
        },
    )
    assert login_resp.status_code == 200
    token_data = login_resp.json()
    assert "access_token" in token_data
    assert "refresh_token" in token_data

    # Exchange refresh token
    refresh_resp = await client.post(
        "/api/v1/auth/refresh",
        json={"refresh_token": token_data["refresh_token"]},
    )
    assert refresh_resp.status_code == 200
    new_token_data = refresh_resp.json()
    assert "access_token" in new_token_data
    assert "refresh_token" in new_token_data


# ==============================================================================
# Rate Limiting Tests
# ==============================================================================

@pytest.mark.asyncio
async def test_rate_limit_headers(client: AsyncClient):
    """Verify rate limit tracking headers are returned on standard requests."""
    resp = await client.get("/api/v1/ml/models", headers={"X-Test-Bypass-RateLimit": "0"})
    assert resp.status_code in [200, 401]
    assert "X-RateLimit-Limit" in resp.headers
    assert "X-RateLimit-Remaining" in resp.headers


# ==============================================================================
# Audit Trail Persistence & API Tests
# ==============================================================================

@pytest.mark.asyncio
async def test_audit_log_recording_and_query_api(
    client: AsyncClient, auth_headers: dict
):
    """Verify action audit logging and GET /api/v1/audit/logs endpoint."""
    async with AsyncSessionLocal() as session:
        # Record direct audit event
        await audit_service.log_action(
            db=session,
            action="ADMIN_CONFIG_UPDATE",
            resource_type="SYSTEM",
            resource_id="SECURITY_POLICY_2026",
            actor_email="admin@kaushalnexus.gov.in",
            status="SUCCESS",
            details={"setting": "RATE_LIMIT_AUTH", "new_value": 15},
        )

    # Query audit logs via API
    resp = await client.get(
        "/api/v1/audit/logs",
        params={"action": "ADMIN_CONFIG_UPDATE"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["total"] >= 1
    assert any(item["action"] == "ADMIN_CONFIG_UPDATE" for item in data["items"])
